version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.0.2
    steps:
      - checkout
      - run:
          name: Install gem dependencies
          command: bundle install
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: RSpec Tests
          command: |
            bundle exec rspec --profile 10 \
              --format RspecJunitFormatter \
              --out test_results/rspec.xml \
              --format documentation \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
